- name: example of ansible facts
  hosts: all
  tasks:
    - name: store kernel version /etc/motd
      copy:
        content: "this is kernel version {{ ansible_kernel }}"
        dest: /etc/motd  

