# /home/abhinku/ansible-learnings/inventory/host_vars
# inventory       = /home/abhinku/ansible-learnings/inventory
# the "hosts" is being picked up from the file '/home/abhinku/ansible-learnings/inventory/hosts-name'
- name: Install the latest packages on VM2 and VM3 hosts
  hosts: all
  tasks:
    - name: install httpd service on VM2 and nginx on VM3
      ansible.builtin.yum:
        name: "{{ sonu_package }}"
        state: present

    - debug:
        msg: "the package {{ sonu_package }} is installed on host ==>> {{ ansible_hostname }}" 

