- hosts: 
    - webserver
  user: abhinku
  become: true
  tasks:
    - name: Dude this is going to create file 
      file:
        path: /tmp/data
        state: touch
    - name: Bhai, this is copying fstab file now.
      copy:
        src: /etc/fstab
        dest: /tmp/

    - name: bhaiya mere, yaar ye crond service restart kar raha hai. yaar thoda thand rakh
      service:
        name: crond
        state: restarted

- hosts:
    - dbserver
  tasks:
    - name: This is going to write a content
      copy:
        content: "hello-world ansible"
        dest: /tmp/abc    
