- name: Example Playbook with Hash
  hosts: localhost
  gather_facts: false
  vars:
    person:
      name: John
      age: 30
      city: New York

  tasks:
    - name: Display Person Information
      debug:
        var: person
  
  tasks:
    - name: Display only city of the person
      debug:
        var: person.city
