---
- name: command vs shell
  hosts: all
  tasks:
    - name: check uptime of linux hosts
      ansible.builtin.command: uptime
      register: command_output

    - name: printing command_output
      ansible.builtin.debug:
        var: command_output.stdout 
