---
- name: shell module demo
  hosts: all
  tasks:
    - name: list files and dirs
      ansible.builtin.shell: 'ls -l *'
      register: command_output

    - name: command output of ls -l
      ansible.builtin.debug:
        var: command_output.stdout_lines 
