# fruits=["apple", "banana", "mango"] -->> with_items
# for x in fruits:  --->> x is item
#     print(x)
#
### here item and with_items are Ansible pre defined keywords
- name: example of useradd in standard loop
  hosts: all
  vars_files: # `vars_files` is used to load variables from external YAML files into your playbook.
    - user-list.yaml
  tasks:
    - name: add user test7 test8 test9
      user:
        name: "{{ item }}"
        state: present
      with_items:
         - "{{ sonu_users }}" 
