- name: this is practicle use of variable
  hosts: webserver
  vars:
    webpkg: httpd
    webroot: /var/www/html
    abhinku:
      - vsftpd
      - ftp
  
  tasks:
    - name: install service
      yum:
        name: "{{ webpkg }}"
        state: present
    - name: start web service
      service:
        name: "{{ webpkg }}"
        state: started
        
    - name: create dir "{{ webroot }}"
      file:
        path: "{{ webroot }}"
        state: directory
        mode: '0755'

    - name: Install other packages, dude!!!
      yum:
        name: "{{ abhinku }}"
        state: installed
